package inventaris_gudang;

import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

import inventaris_gudang.account.karyawan;
import inventaris_gudang.master.barang;
import inventaris_gudang.master.supplier;
import inventaris_gudang.master.kategori;
import inventaris_gudang.transaksi.barang_masuk;
import inventaris_gudang.transaksi.barang_keluar;

public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        
        initComponents();
        load_table();
        setIconImage();
        
        String username = session.get_username();
        welcome_message.setText("Selamat datang kembali, " + username);
        
        int level = session.get_level();

            if (level == 1) {

                menu_profile.setVisible(true);
                menu_logout.setVisible(true);

                menu_logout.setEnabled(true);
                menu_logout.setVisible(true);

                button_barang_masuk.setVisible(true);
                button_barang_masuk.setEnabled(true);

                button_barang_keluar.setVisible(true);
                button_barang_keluar.setEnabled(true);

                menu_kategori.setEnabled(true);
                menu_kategori.setVisible(true);

            } else if (level == 2) {

                menu_profile.setEnabled(false);
                menu_profile.setVisible(false);

                menu_kategori.setEnabled(false);
                menu_kategori.setVisible(false);

            }

    }

    public void load_table() {

        DefaultTableModel model = new DefaultTableModel();

            model.addColumn("#");
            model.addColumn("Kode");
            model.addColumn("Nama");
            model.addColumn("Kategori");
            model.addColumn("Satuan");
            model.addColumn("Stock");
            
        try {

            String sql = "SELECT barang.id_barang, barang.kode_barang, barang.nama_barang, kategori.nama_kategori as kategori, barang.satuan_barang, barang.stock_barang FROM barang JOIN kategori ON kategori.id_kategori = barang.id_kategories";

                java.sql.Connection con = (Connection) db_connection.configDB();
                java.sql.Statement stm = con.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {

                model.addRow(new Object[] {

                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6),

                });

            }

            table.setModel(model);
            
        } catch (Exception e) {

            System.out.println("Error occured: " + e.getMessage());
            
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        card = new javax.swing.JPanel();
        button_barang_masuk = new javax.swing.JButton();
        button_barang_keluar = new javax.swing.JButton();
        button_logout = new javax.swing.JButton();
        button_refresh = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        welcome_message = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        menu = new javax.swing.JMenuBar();
        Account = new javax.swing.JMenu();
        menu_profile = new javax.swing.JMenuItem();
        menu_logout = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        menu_supplier = new javax.swing.JMenuItem();
        menu_barang = new javax.swing.JMenuItem();
        menu_kategori = new javax.swing.JMenuItem();
        transaksi = new javax.swing.JMenu();
        menu_barang_masuk = new javax.swing.JMenuItem();
        menu_barang_keluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");

        navbar.setBackground(new java.awt.Color(102, 102, 102));

        title.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("INVENTARIS GUDANG");

        card.setBackground(new java.awt.Color(0, 255, 204));

        button_barang_masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/big-parcel-32.png"))); // NOI18N
        button_barang_masuk.setOpaque(false);
        button_barang_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_barang_masukActionPerformed(evt);
            }
        });

        button_barang_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/open-parcel-32.png"))); // NOI18N
        button_barang_keluar.setOpaque(false);
        button_barang_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_barang_keluarActionPerformed(evt);
            }
        });

        button_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shutdown-32.png"))); // NOI18N
        button_logout.setOpaque(false);
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardLayout = new javax.swing.GroupLayout(card);
        card.setLayout(cardLayout);
        cardLayout.setHorizontalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_barang_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_barang_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(button_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        cardLayout.setVerticalGroup(
            cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(button_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_barang_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_barang_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap())
        );

        button_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reload.png"))); // NOI18N
        button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_refresh)
                        .addGap(133, 133, 133)))
                .addComponent(card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(navbarLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(navbar, java.awt.BorderLayout.PAGE_END);

        content.setBackground(new java.awt.Color(255, 255, 255));

        welcome_message.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        welcome_message.setForeground(new java.awt.Color(0, 0, 0));
        welcome_message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome_message.setText("welcome");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome_message, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcome_message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        menu.setBackground(new java.awt.Color(60, 60, 60));
        menu.setForeground(new java.awt.Color(60, 63, 65));

        Account.setBackground(new java.awt.Color(60, 60, 60));
        Account.setText("Account");

        menu_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user-20.png"))); // NOI18N
        menu_profile.setText("Karyawan");
        menu_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_profileActionPerformed(evt);
            }
        });
        Account.add(menu_profile);

        menu_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shutdown-20.png"))); // NOI18N
        menu_logout.setText("Logout");
        menu_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_logoutActionPerformed(evt);
            }
        });
        Account.add(menu_logout);

        menu.add(Account);

        master.setText("Master");
        master.setToolTipText("");

        menu_supplier.setText("Supplier");
        menu_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_supplierActionPerformed(evt);
            }
        });
        master.add(menu_supplier);

        menu_barang.setText("Barang");
        menu_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_barangActionPerformed(evt);
            }
        });
        master.add(menu_barang);

        menu_kategori.setText("Kategori Barang");
        menu_kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_kategoriActionPerformed(evt);
            }
        });
        master.add(menu_kategori);

        menu.add(master);

        transaksi.setText("Transaksi");

        menu_barang_masuk.setText("Barang Masuk");
        menu_barang_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_barang_masukActionPerformed(evt);
            }
        });
        transaksi.add(menu_barang_masuk);

        menu_barang_keluar.setText("Barang Keluar");
        menu_barang_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_barang_keluarActionPerformed(evt);
            }
        });
        transaksi.add(menu_barang_keluar);

        menu.add(transaksi);

        setJMenuBar(menu);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_refreshActionPerformed
        
        load_table();
        
    }//GEN-LAST:event_button_refreshActionPerformed

    private void button_barang_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_barang_masukActionPerformed
        
        barang_masuk barang_masukWindow = new barang_masuk(this, true);
        barang_masukWindow.setVisible(true);
        
    }//GEN-LAST:event_button_barang_masukActionPerformed

    private void button_barang_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_barang_keluarActionPerformed
        
        barang_keluar barang_keluarWindow = new barang_keluar(this, true);
        barang_keluarWindow.setVisible(true);
        
    }//GEN-LAST:event_button_barang_keluarActionPerformed


    // < Buttons >

        private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {

            new login().setVisible(true);
            this.dispose();
            
        }

        private void menu_logoutActionPerformed(java.awt.event.ActionEvent evt) {

            new login().setVisible(true);
            this.dispose();
            
        }

        private void menu_profileActionPerformed(java.awt.event.ActionEvent evt) {

            karyawan karyawanWindow = new karyawan(this, true);
            karyawanWindow.setVisible(true);
        
        }

        private void menu_supplierActionPerformed(java.awt.event.ActionEvent evt) {

            supplier supplierWindow = new supplier(this, true);
            supplierWindow.setVisible(true);
        
        }

        private void menu_barangActionPerformed(java.awt.event.ActionEvent evt) {

            barang barangWindow = new barang(this, true);
            barangWindow.setVisible(true);
        
        }

        private void menu_kategoriActionPerformed(java.awt.event.ActionEvent evt) {
            
            kategori kategoriWindow = new kategori(this, true);
            kategoriWindow.setVisible(true);

        }

        private void menu_barang_masukActionPerformed(java.awt.event.ActionEvent evt) {
            
            barang_masuk barang_masukWindow = new barang_masuk(this, true);
            barang_masukWindow.setVisible(true);
            
        }

        private void menu_barang_keluarActionPerformed(java.awt.event.ActionEvent evt) {
            
            barang_keluar barang_keluarWindow = new barang_keluar(this, true);
            barang_keluarWindow.setVisible(true);
            
        }

    // < End Buttons >

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    private void setIconImage() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("favicon.png")));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Account;
    private javax.swing.JButton button_barang_keluar;
    private javax.swing.JButton button_barang_masuk;
    private javax.swing.JButton button_logout;
    private javax.swing.JButton button_refresh;
    private javax.swing.JPanel card;
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu master;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menu_barang;
    private javax.swing.JMenuItem menu_barang_keluar;
    private javax.swing.JMenuItem menu_barang_masuk;
    private javax.swing.JMenuItem menu_kategori;
    private javax.swing.JMenuItem menu_logout;
    private javax.swing.JMenuItem menu_profile;
    private javax.swing.JMenuItem menu_supplier;
    private javax.swing.JPanel navbar;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    private javax.swing.JMenu transaksi;
    private javax.swing.JLabel welcome_message;
    // End of variables declaration//GEN-END:variables
}
