package inventaris_gudang.account;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;

import java.sql.Connection;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

import inventaris_gudang.db_connection;
import inventaris_gudang.session;


public class karyawan extends javax.swing.JDialog {

    public karyawan(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();

        setIconImage();
        load_table();
        cleaner();

        // Disable button

            btn_enable(false);
            button_save.setText("Save");

    }

    public void load_table() {

        DefaultTableModel model = new DefaultTableModel();

            model.addColumn("#");
            model.addColumn("Nickname");
            model.addColumn("Username");
            model.addColumn("Email");
            model.addColumn("Password");

        try {

            String sql = "SELECT * FROM user";

                java.sql.Connection con = (Connection) db_connection.configDB();
                java.sql.Statement stm = con.createStatement();
                java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {

                model.addRow(new Object[] {

                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),

                });

            }

            table.setModel(model);

            String count_data = String.valueOf(table.getRowCount());
            jumlah_label.setText("Jumlah data : " + count_data);

        } catch (Exception e) {

            System.out.println("Error occured: " + e.getMessage());

        }

    }

    public void load_table_view() {

        int row = table.getSelectedRow();
        String row_id = (table.getModel().getValueAt(row, 0).toString());

        id_input.setText(row_id);

        btn_enable(true);

        if (row_id.equals(Integer.toString(session.get_id()))) {

            button_delete.setEnabled(false);

        }

    }

    private void btn_enable(boolean x) {

        button_edit.setEnabled(x);
        button_delete.setEnabled(x);

    }

    private void cleaner() {

        nickname_input.setText(null);
        username_input.setText(null);
        password_input.setText(null);
        confirm_password_input.setText(null);
        id_input.setText(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable(){     public boolean isCellEditable(int rowIndex, int colIndex) {         return false;     } };
        button_add = new javax.swing.JButton();
        button_edit = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_refresh = new javax.swing.JButton();
        form_title = new javax.swing.JLabel();
        card_form = new javax.swing.JPanel();
        nickname_label = new javax.swing.JLabel();
        nickname_input = new javax.swing.JTextField();
        username_label = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        confirm_password_label = new javax.swing.JLabel();
        confirm_password_input = new javax.swing.JPasswordField();
        button_save = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        jumlah_label = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        id_input = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Karyawan");
        setBackground(new java.awt.Color(60, 60, 60));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 255, 204));

        title.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Data Karyawan");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, -1));

        content.setBackground(new java.awt.Color(102, 102, 102));
        content.setForeground(new java.awt.Color(60, 63, 65));
        content.setToolTipText("");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Nickname", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setColumnSelectionAllowed(true);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        button_add.setForeground(new java.awt.Color(0, 0, 0));
        button_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        button_add.setText("Add");
        button_add.setIconTextGap(8);
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        button_edit.setForeground(new java.awt.Color(0, 0, 0));
        button_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        button_edit.setText("Edit");
        button_edit.setIconTextGap(8);
        button_edit.setPreferredSize(new java.awt.Dimension(68, 32));
        button_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_editActionPerformed(evt);
            }
        });

        button_delete.setForeground(new java.awt.Color(0, 0, 0));
        button_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        button_delete.setText("Delete");
        button_delete.setIconTextGap(8);
        button_delete.setPreferredSize(new java.awt.Dimension(68, 32));
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/reload.png"))); // NOI18N
        button_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_refreshActionPerformed(evt);
            }
        });

        form_title.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        form_title.setForeground(new java.awt.Color(255, 255, 255));
        form_title.setText("Tambah Data");

        card_form.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        card_form.setOpaque(false);
        card_form.setPreferredSize(new java.awt.Dimension(370, 230));
        card_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nickname_label.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        nickname_label.setForeground(new java.awt.Color(255, 255, 255));
        nickname_label.setText("Nickname");
        card_form.add(nickname_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        card_form.add(nickname_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 210, -1));

        username_label.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        username_label.setForeground(new java.awt.Color(255, 255, 255));
        username_label.setText("Username");
        card_form.add(username_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        username_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                username_inputKeyTyped(evt);
            }
        });
        card_form.add(username_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 210, -1));

        password_label.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        password_label.setForeground(new java.awt.Color(255, 255, 255));
        password_label.setText("Password");
        card_form.add(password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        password_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                password_inputKeyTyped(evt);
            }
        });
        card_form.add(password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 210, -1));

        confirm_password_label.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        confirm_password_label.setForeground(new java.awt.Color(255, 255, 255));
        confirm_password_label.setText("Confirm Password");
        card_form.add(confirm_password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        card_form.add(confirm_password_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 210, -1));

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });
        card_form.add(button_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 130, -1));

        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });
        card_form.add(button_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jumlah_label.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jumlah_label.setForeground(new java.awt.Color(255, 255, 255));
        jumlah_label.setText("Jumlah data");

        id_label.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        id_label.setForeground(new java.awt.Color(255, 255, 255));
        id_label.setText("ID");

        id_input.setEditable(false);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentLayout.createSequentialGroup()
                            .addComponent(button_add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(button_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(button_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(button_refresh))
                        .addGroup(contentLayout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(form_title)
                                .addComponent(card_form, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(contentLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jumlah_label)
                            .addGap(312, 312, 312)
                            .addComponent(id_label)
                            .addGap(6, 6, 6)
                            .addComponent(id_input, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(button_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(6, 6, 6)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentLayout.createSequentialGroup()
                            .addComponent(form_title)
                            .addGap(6, 6, 6)
                            .addComponent(card_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(12, 12, 12)
                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contentLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jumlah_label))
                        .addComponent(id_label)
                        .addComponent(id_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, 850, 470));
        content.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // < Buttons >

        private void button_addActionPerformed(java.awt.event.ActionEvent evt) {
           
            form_title.setForeground(Color.white);
            form_title.setText("Tambah Data");

            table.clearSelection();
            cleaner();

            btn_enable(false);

            button_save.setText("Save");
            nickname_input.requestFocus();

        }

        private void button_editActionPerformed(java.awt.event.ActionEvent evt) {
        
            String row_id = id_input.getText();

            if (!"0".equals(row_id)) {

                try {

                    button_save.setText("Save Change");

                    String sql = "SELECT user.id_user, user.nickname, user.username FROM user WHERE user.id_user ='"+ row_id +"'";

                        java.sql.Connection con = (Connection) db_connection.configDB();
                        java.sql.Statement stm = con.createStatement();
                        java.sql.ResultSet res = stm.executeQuery(sql);

                    if (res.next()) {
                        
                        String code_name = res.getString("username");

                        form_title.setForeground(Color.white);
                        form_title.setText("Editing Data | " + code_name);
                        id_input.setText(res.getString("id_user"));
                        nickname_input.setText(res.getString("nickname"));
                        username_input.setText(code_name);
                        nickname_input.requestFocus();

                    }

                } catch (Exception e) {

                    System.out.println("Error occured: " + e.getMessage());

                }

            }
        
        }

        private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {

            int valid = JOptionPane.showConfirmDialog(null, "Are you sure want to delete this data?", "Confirm", JOptionPane.OK_CANCEL_OPTION);

            if (valid == 0) {

                try {

                    String row_id = id_input.getText();
                    String sql = "DELETE FROM user WHERE id_user = '"+ row_id + "'";

                        java.sql.Connection con = (Connection) db_connection.configDB();
                        java.sql.Statement stm = con.createStatement();
                        stm.executeUpdate(sql);

                        JOptionPane.showMessageDialog(null, "Data has confirmed being deleted.");
                        button_add.doClick();

                        load_table();

                } catch (Exception e) {

                    System.out.println("Error occured: " + e.getMessage());

                }

            }
        
        }

        private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {

            String row_id = id_input.getText();
            String row_nickname = nickname_input.getText();
            String row_username = username_input.getText();

            char[] passwordChars = password_input.getPassword();
            char[] confirm_passwordChars = confirm_password_input.getPassword();

            String row_password = new String(passwordChars);
            String row_confirm_password = new String(confirm_passwordChars);

            if (!(row_password.equals(row_confirm_password))) {

                JOptionPane.showMessageDialog(null, "Oops! you have entered the wrong password.", "Failed to attempt", JOptionPane.ERROR_MESSAGE);

                confirm_password_input.setText(null);
                confirm_password_input.requestFocus();

            } else {

                int code = 0;

                if (!"".equals(row_nickname) && !"".equals(row_username) && !"".equals(row_password) && !"".equals(row_confirm_password)) {

                    if (password_input.getPassword().length == 0 || confirm_password_input.getPassword().length == 0) {

                        JOptionPane.showMessageDialog(null, "There was empty field!");

                    } else {

                        try {

                            String sql = "SELECT COUNT(user.id_user) as count FROM user WHERE user.username='"+ row_username +"'";

                                java.sql.Connection con = (Connection) db_connection.configDB();
                                java.sql.Statement stm = con.createStatement();
                                java.sql.ResultSet res = stm.executeQuery(sql);

                                res.next();

                                code = res.getInt("count");

                        } catch (Exception e) {

                            System.out.println("Error occured: " + e.getMessage());

                        }

                        if ("".equals(row_id)) {

                            if (code == 0) {

                                try {

                                    String sql = "INSERT INTO user(nickname, username, password, _userLevel) VALUES ('"+ row_nickname +"', '"+ row_username +"', '"+ row_password +"', '2')";

                                        java.sql.Connection con = (Connection) db_connection.configDB();
                                        java.sql.Statement stm = con.createStatement();
                                        stm.executeUpdate(sql);

                                    JOptionPane.showMessageDialog(null, "Successfully added new data.");

                                    button_add.doClick();
                                    load_table();

                                } catch (Exception e) {

                                    System.out.println("Error occured: " + e.getMessage());

                                }

                            } else {

                                JOptionPane.showMessageDialog(null, "This username have ever been stored before.", "Failed to attempt", JOptionPane.ERROR_MESSAGE);

                            }

                        } else {

                            if (code == 0 || row_id.equals(row_id)) {

                                try {

                                    String sql = "UPDATE user SET nickname='"+ row_nickname +"', username='"+ row_username +"', password='"+ row_password +"' WHERE id_user = '"+ row_id +"' ";

                                        java.sql.Connection con = (Connection) db_connection.configDB();
                                        java.sql.Statement stm = con.createStatement();
                                        stm.executeUpdate(sql);

                                    JOptionPane.showMessageDialog(null, "Successfully edited data.");

                                    button_add.doClick();
                                    load_table();

                                } catch (Exception e) {

                                    System.out.println("Error occurred: " + e.getMessage());

                                }

                            }

                        }

                    }

                } else {

                    JOptionPane.showMessageDialog(null, "There was empty field!");
                    
                }

            }
        
        }

        private void tableMouseClicked(java.awt.event.MouseEvent evt) {
            
            load_table_view();

        }

        private void tableMouseReleased(java.awt.event.MouseEvent evt) {
            
            load_table_view();

        }

        private void tableKeyReleased(java.awt.event.KeyEvent evt) {
            
            load_table_view();

        }

        private void button_refreshActionPerformed(java.awt.event.ActionEvent evt) {
            
            load_table();
            
        }

        private void username_inputKeyTyped(java.awt.event.KeyEvent evt) {

            char type = evt.getKeyChar();

                if (type == KeyEvent.VK_SPACE) {

                    JOptionPane.showMessageDialog(null, "Oops! username may not contains space!", "Illegal Input", JOptionPane.ERROR_MESSAGE);
                    evt.consume();

                }

        }

        private void password_inputKeyTyped(java.awt.event.KeyEvent evt) {

            char type = evt.getKeyChar();

                if (type == KeyEvent.VK_SPACE) {

                    JOptionPane.showMessageDialog(null, "Oops! password may not contains space!", "Illegal Input", JOptionPane.ERROR_MESSAGE);
                    evt.consume();

                }

        }

        private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {

            button_add.doClick();
        
        }
        
    // < End Buttons >

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                karyawan dialog = new karyawan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void setIconImage() {
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/inventaris_gudang/favicon.png")));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_edit;
    private javax.swing.JButton button_refresh;
    private javax.swing.JButton button_save;
    private javax.swing.JPanel card_form;
    private javax.swing.JPasswordField confirm_password_input;
    private javax.swing.JLabel confirm_password_label;
    private javax.swing.JPanel content;
    private javax.swing.JLabel form_title;
    private javax.swing.JPanel header;
    private javax.swing.JTextField id_input;
    private javax.swing.JLabel id_label;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jumlah_label;
    private javax.swing.JTextField nickname_input;
    private javax.swing.JLabel nickname_label;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel password_label;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
